CREATE TABLE GUEST (
    SABUN NUMBER(5) PRIMARY KEY,
    NAME VARCHAR2(30),
    NALJA DATE,
    PAY NUMBER(20)
);
INSERT INTO GUEST VALUES (1111, 'PSJ', SYSDATE, 5000);
INSERT INTO GUEST VALUES (2222, 'CWS', SYSDATE, 5000);

SELECT ROWNUM AS RN, SABUN, NAME, NALJA, PAY FROM GUEST ORDER BY SABUN;
SELECT COUNT(*) CNT FROM GUEST;

SELECT NVL(MAX(SABUN),0) + 1111 AS SABUN FROM GUEST;